// Code generated by audit-eval -calibrate; DO NOT EDIT.

package core

// auditCalibratedScores maps each scored detector that has offline oracle
// samples to its fitted P(survive|fired) = empirical precision over the
// benchmark corpus (AUDIT_PLAN §9.3). Detectors absent here keep the prior
// score hard-coded in their inspect().
var auditCalibratedScores = map[string]float64{
	"argument-swap-blind": 1.00, // n=1
	"loose-count":         1.00, // n=1
	"unpinned-arg":        1.00, // n=4
}
