package testigogen

import (
	"bytes"
	"fmt"
	"go/format"
	"go/token"
	"go/types"
	"reflect"
	"sort"
	"strings"
)

// Generate renders the source selected by opts.
func Generate(opts Options) ([]byte, error) {
	model, err := loadModel(opts)
	if err != nil {
		return nil, err
	}
	g := &generator{
		model:       model,
		imports:     newImportSet(model.pkg.PkgPath),
		randomFuncs: make(map[string]string),
	}
	if err := g.prepare(); err != nil {
		return nil, err
	}
	if err := g.render(); err != nil {
		return nil, err
	}

	var source bytes.Buffer
	source.WriteString("// Code generated by testigo-gen. DO NOT EDIT.\n\n")
	fmt.Fprintf(&source, "package %s\n\n", model.pkg.Name)
	source.WriteString(g.imports.render())
	source.Write(g.body.Bytes())

	formatted, err := format.Source(source.Bytes())
	if err != nil {
		return nil, fmt.Errorf("testigo-gen: format generated source: %w\n%s", err, source.String())
	}
	return formatted, nil
}

type generator struct {
	model       *model
	imports     *importSet
	body        bytes.Buffer
	randomFuncs map[string]string
	spies       []spyModel
}

func (g *generator) prepare() error {
	names := make(map[string]string)
	for _, entry := range g.model.artifacts {
		if entry.fixture {
			named, _, _ := namedStruct(entry.typeOf)
			function := "Random" + named.Obj().Name()
			key := canonicalType(entry.typeOf)
			if previous, exists := names[function]; exists && previous != key {
				return fmt.Errorf("testigo-gen: random function name %s collides for %s and %s", function, previous, key)
			}
			names[function] = key
			g.randomFuncs[key] = function
		}
	}
	return nil
}

func (g *generator) render() error {
	renderedRandom := make(map[string]bool)
	for _, entry := range g.model.artifacts {
		if entry.fixture {
			key := canonicalType(entry.typeOf)
			if !renderedRandom[key] {
				if err := g.renderRandom(entry.typeOf, g.randomFuncs[key]); err != nil {
					return fmt.Errorf("testigo-gen: %s: %w", entry.name, err)
				}
				renderedRandom[key] = true
			}
			if err := g.renderFixture(entry); err != nil {
				return err
			}
		}
		if entry.spy {
			spy, err := g.renderSpy(entry)
			if err != nil {
				return err
			}
			g.spies = append(g.spies, spy)
		}
		if entry.stub || entry.errorStub {
			var fixture *artifact
			if entry.stubFixture != "" {
				resolved, ok := g.fixtureArtifact(entry.stubFixture)
				if !ok {
					return fmt.Errorf("testigo-gen: %s: fixture %q not found", entry.name, entry.stubFixture)
				}
				fixture = &resolved
			}
			if err := g.renderStub(entry, fixture, entry.errorStub); err != nil {
				return err
			}
		}
		if entry.seederMethod != "" {
			if err := g.renderSeeder(entry); err != nil {
				return err
			}
		}
	}
	if len(g.spies) > 0 {
		g.renderDoubles()
	}
	return nil
}

func (g *generator) fixtureArtifact(name string) (artifact, bool) {
	for _, entry := range g.model.artifacts {
		if entry.name == name && entry.fixture {
			return entry, true
		}
	}
	return artifact{}, false
}

func (g *generator) renderRandom(value types.Type, function string) error {
	_, structure, ok := namedStruct(value)
	if !ok {
		return fmt.Errorf("random generation requires a named struct")
	}
	typeName := g.imports.typeString(value)
	fmt.Fprintf(&g.body, "// %s returns a fresh random %s.\n", function, typeName)
	fmt.Fprintf(&g.body, "func %s() %s {\n", function, typeName)
	fmt.Fprintf(&g.body, "\treturn %s{\n", typeName)
	for i := range structure.NumFields() {
		field := structure.Field(i)
		if !g.fieldAccessible(field) || fieldTagSkipped(structure.Tag(i)) {
			continue
		}
		expression, ok := g.randomExpression(field.Name(), field.Type())
		if !ok {
			continue
		}
		fmt.Fprintf(&g.body, "\t\t%s: %s,\n", field.Name(), expression)
	}
	g.body.WriteString("\t}\n}\n\n")
	return nil
}

func (g *generator) renderFixture(entry artifact) error {
	_, structure, _ := namedStruct(entry.typeOf)
	typeName := g.imports.typeString(entry.typeOf)
	fixtureAlias := g.imports.add("github.com/lautaromei/testigo/fixture", "fixture")
	builderName := lowerFirst(entry.name) + "Builder"
	randomFunction := g.randomFuncs[canonicalType(entry.typeOf)]
	baseFunction := randomFunction
	if entry.baseFunc != "" {
		baseFunction = entry.baseFunc
	}

	fmt.Fprintf(&g.body, "type %s struct {\n\t%s.Builder[%s]\n}\n\n", builderName, fixtureAlias, typeName)
	fmt.Fprintf(&g.body, "// %s is the generated fluent fixture for %s.\n", entry.name, typeName)
	fmt.Fprintf(&g.body, "var %s = %s{Builder: %s.NewGeneratedBuilder(%s)}\n\n", entry.name, builderName, fixtureAlias, baseFunction)

	for i := range structure.NumFields() {
		field := structure.Field(i)
		if !g.fieldAccessible(field) || fieldTagSkipped(structure.Tag(i)) {
			continue
		}
		fieldType := g.imports.typeString(field.Type())
		method := "With" + field.Name()
		fmt.Fprintf(&g.body, "// %s sets %s on a derived fixture.\n", method, field.Name())
		fmt.Fprintf(&g.body, "func (b %s) %s(value %s) %s {\n", builderName, method, fieldType, builderName)
		fmt.Fprintf(&g.body, "\tb.Builder = b.Set(func(target *%s) { target.%s = value })\n", typeName, field.Name())
		g.body.WriteString("\treturn b\n}\n\n")
	}

	if entry.memdbKey != "" {
		key := findField(structure, entry.memdbKey)
		memdbAlias := g.imports.add("github.com/lautaromei/testigo/memdb", "memdb")
		keyType := g.imports.typeString(key.Type())
		constructor := "New" + entry.name + "DB"
		fmt.Fprintf(&g.body, "// %s creates an in-memory database keyed by %s.\n", constructor, entry.memdbKey)
		fmt.Fprintf(&g.body, "func %s(seed ...%s) %s.DB[%s] {\n", constructor, typeName, memdbAlias, typeName)
		fmt.Fprintf(&g.body, "\treturn %s.New(func(value %s) %s { return value.%s }, seed...)\n", memdbAlias, typeName, keyType, entry.memdbKey)
		g.body.WriteString("}\n\n")
		fmt.Fprintf(&g.body, "// DB creates an in-memory database for %s.\n", entry.name)
		fmt.Fprintf(&g.body, "func (%s) DB(seed ...%s) %s.DB[%s] { return %s(seed...) }\n\n", builderName, typeName, memdbAlias, typeName, constructor)
	}
	return nil
}

func (g *generator) fieldAccessible(field *types.Var) bool {
	return field.Exported() || field.Pkg() == nil || field.Pkg().Path() == g.model.pkg.PkgPath
}

func fieldTagSkipped(raw string) bool {
	value, ok := reflect.StructTag(raw).Lookup(tagName)
	return ok && strings.TrimSpace(value) == "-"
}

func (g *generator) randomExpression(fieldName string, value types.Type) (string, bool) {
	if constants := enumConstants(value, g.model.pkg.PkgPath, g.imports); len(constants) > 0 {
		randomAlias := g.imports.add("github.com/lautaromei/testigo/random", "random")
		return fmt.Sprintf("%s.Pick(%s)", randomAlias, strings.Join(constants, ", ")), true
	}

	if named, _, ok := namedStruct(value); ok {
		if named.Obj().Pkg() != nil && named.Obj().Pkg().Path() == "time" && named.Obj().Name() == "Time" {
			randomAlias := g.imports.add("github.com/lautaromei/testigo/random", "random")
			return randomAlias + ".Date()", true
		}
		if function, exists := g.randomFuncs[canonicalType(value)]; exists {
			return function + "()", true
		}
		return "", false
	}

	basic, ok := types.Unalias(value).Underlying().(*types.Basic)
	if !ok {
		return "", false
	}
	normalized := strings.ToLower(strings.ReplaceAll(fieldName, "_", ""))
	supported := basic.Info()&(types.IsString|types.IsBoolean|types.IsInteger|types.IsFloat) != 0
	if !supported {
		return "", false
	}
	randomAlias := g.imports.add("github.com/lautaromei/testigo/random", "random")
	var expression string
	generatedKind := basic.Kind()
	switch basic.Kind() {
	case types.String:
		switch {
		case strings.Contains(normalized, "email"):
			expression = randomAlias + ".Email()"
		case normalized == "firstname":
			expression = randomAlias + ".FirstName()"
		case normalized == "lastname":
			expression = randomAlias + ".LastName()"
		case normalized == "name" || strings.HasSuffix(normalized, "name"):
			expression = randomAlias + ".Name()"
		case strings.Contains(normalized, "path"):
			expression = randomAlias + ".Path()"
		default:
			expression = randomAlias + ".String(12)"
		}
	case types.Bool:
		expression = randomAlias + ".Bool()"
	case types.Int, types.Int8, types.Int16, types.Int32, types.Int64:
		generatedKind = types.Int
		if normalized == "id" || strings.HasSuffix(normalized, "id") {
			expression = randomAlias + ".ID()"
		} else {
			expression = randomAlias + ".Int()"
		}
	case types.Uint, types.Uint8, types.Uint16, types.Uint32, types.Uint64, types.Uintptr:
		generatedKind = types.Int
		expression = randomAlias + ".ID()"
	case types.Float32, types.Float64:
		generatedKind = types.Float64
		expression = randomAlias + ".Float()"
	default:
		return "", false
	}
	if !isExactBasic(value, generatedKind) {
		expression = g.imports.typeString(value) + "(" + expression + ")"
	}
	return expression, true
}

func enumConstants(value types.Type, current string, imports *importSet) []string {
	named, ok := types.Unalias(value).(*types.Named)
	if !ok || named.Obj().Pkg() == nil {
		return nil
	}
	pkg := named.Obj().Pkg()
	var constants []string
	for _, name := range pkg.Scope().Names() {
		object, ok := pkg.Scope().Lookup(name).(*types.Const)
		if !ok || !types.Identical(object.Type(), value) {
			continue
		}
		if pkg.Path() != current && !object.Exported() {
			continue
		}
		qualifier := imports.qualifier(pkg)
		if qualifier != "" {
			name = qualifier + "." + name
		}
		constants = append(constants, name)
	}
	sort.Strings(constants)
	return constants
}

func isExactBasic(value types.Type, kind types.BasicKind) bool {
	basic, ok := types.Unalias(value).(*types.Basic)
	return ok && basic.Kind() == kind
}

func canonicalType(value types.Type) string {
	return types.TypeString(value, func(pkg *types.Package) string {
		if pkg == nil {
			return ""
		}
		return pkg.Path()
	})
}

func validIdentifier(value string) bool {
	return token.IsIdentifier(value) && !token.Lookup(value).IsKeyword()
}
