// Code generated by testigo-gen. DO NOT EDIT.

package testkit

import (
	"context"
	"testing"
	"time"

	"github.com/lautaromei/testigo"
	"github.com/lautaromei/testigo/fixture"
	"github.com/lautaromei/testigo/internal/testigogen/testdata/domain"
	"github.com/lautaromei/testigo/memdb"
	"github.com/lautaromei/testigo/random"
	"github.com/lautaromei/testigo/seeder"
)

// RandomUser returns a fresh random domain.User.
func RandomUser() domain.User {
	return domain.User{
		ID:        random.ID(),
		Balance:   int64(random.Int()),
		Name:      random.Name(),
		Email:     random.Email(),
		Active:    random.Bool(),
		Role:      random.Pick(domain.RoleAdmin, domain.RoleMember),
		CreatedAt: random.Date(),
	}
}

type defaultUsersBuilder struct {
	fixture.Builder[domain.User]
}

// DefaultUsers is the generated fluent fixture for domain.User.
var DefaultUsers = defaultUsersBuilder{Builder: fixture.NewGeneratedBuilder(defaultUser)}

// WithID sets ID on a derived fixture.
func (b defaultUsersBuilder) WithID(value int) defaultUsersBuilder {
	b.Builder = b.Set(func(target *domain.User) { target.ID = value })
	return b
}

// WithBalance sets Balance on a derived fixture.
func (b defaultUsersBuilder) WithBalance(value int64) defaultUsersBuilder {
	b.Builder = b.Set(func(target *domain.User) { target.Balance = value })
	return b
}

// WithName sets Name on a derived fixture.
func (b defaultUsersBuilder) WithName(value string) defaultUsersBuilder {
	b.Builder = b.Set(func(target *domain.User) { target.Name = value })
	return b
}

// WithEmail sets Email on a derived fixture.
func (b defaultUsersBuilder) WithEmail(value string) defaultUsersBuilder {
	b.Builder = b.Set(func(target *domain.User) { target.Email = value })
	return b
}

// WithActive sets Active on a derived fixture.
func (b defaultUsersBuilder) WithActive(value bool) defaultUsersBuilder {
	b.Builder = b.Set(func(target *domain.User) { target.Active = value })
	return b
}

// WithRole sets Role on a derived fixture.
func (b defaultUsersBuilder) WithRole(value domain.Role) defaultUsersBuilder {
	b.Builder = b.Set(func(target *domain.User) { target.Role = value })
	return b
}

// WithCreatedAt sets CreatedAt on a derived fixture.
func (b defaultUsersBuilder) WithCreatedAt(value time.Time) defaultUsersBuilder {
	b.Builder = b.Set(func(target *domain.User) { target.CreatedAt = value })
	return b
}

// WithTags sets Tags on a derived fixture.
func (b defaultUsersBuilder) WithTags(value []string) defaultUsersBuilder {
	b.Builder = b.Set(func(target *domain.User) { target.Tags = value })
	return b
}

// MailerSpy implements domain.Mailer and records every call.
type MailerSpy struct {
	testigo.Spy
	wrapped *testigo.Reference[domain.Mailer]
}

var _ domain.Mailer = (*MailerSpy)(nil)

func (s *MailerSpy) Broadcast(ctx context.Context, to ...string) (int, error) {
	s.Call(ctx, to)
	return s.wrapped.Get().Broadcast(ctx, to...)
}

func (s *MailerSpy) Ping() {
	s.Call()
	s.wrapped.Get().Ping()
}

func (s *MailerSpy) Send(ctx context.Context, to string) error {
	s.Call(ctx, to)
	return s.wrapped.Get().Send(ctx, to)
}

// NewMailerSpy composes and registers a spy around the supplied implementation.
func NewMailerSpy(t *testing.T, wrapped domain.Mailer) *MailerSpy {
	value := &MailerSpy{wrapped: testigo.Ref(wrapped)}
	return testigo.NewDouble(t, value)
}

// RepoStub implements domain.UserRepository using values from the supplied fixture.
type RepoStub struct {
	base usersBuilder
}

var _ domain.UserRepository = (*RepoStub)(nil)

func (s *RepoStub) Upsert(ctx context.Context, user domain.User) (domain.User, error) {
	result0 := s.base.Bare()
	var result1 error
	return result0, result1
}

// NewRepoStub creates a stub backed by the supplied fixture.
func NewRepoStub(base usersBuilder) *RepoStub { return &RepoStub{base: base} }

// RepoErrorsErrorStub implements domain.UserRepository and returns the configured error.
type RepoErrorsErrorStub struct {
	base usersBuilder
	err  error
}

var _ domain.UserRepository = (*RepoErrorsErrorStub)(nil)

func (s *RepoErrorsErrorStub) Upsert(ctx context.Context, user domain.User) (domain.User, error) {
	result0 := s.base.Bare()
	var result1 error = s.err
	return result0, result1
}

// NewRepoErrorsErrorStub creates an error stub backed by the supplied fixture.
func NewRepoErrorsErrorStub(base usersBuilder, err error) *RepoErrorsErrorStub {
	return &RepoErrorsErrorStub{base: base, err: err}
}

// UserRepoSpy implements domain.UserRepository and records every call.
type UserRepoSpy struct {
	testigo.Spy
	wrapped *testigo.Reference[domain.UserRepository]
}

var _ domain.UserRepository = (*UserRepoSpy)(nil)

func (s *UserRepoSpy) Upsert(ctx context.Context, user domain.User) (domain.User, error) {
	s.Call(ctx, user)
	return s.wrapped.Get().Upsert(ctx, user)
}

// NewUserRepoSpy composes and registers a spy around the supplied implementation.
func NewUserRepoSpy(t *testing.T, wrapped domain.UserRepository) *UserRepoSpy {
	value := &UserRepoSpy{wrapped: testigo.Ref(wrapped)}
	return testigo.NewDouble(t, value)
}

// NewUserRepoSeeder adapts domain.UserRepository.Upsert to a typed seeder.
func NewUserRepoSeeder(t testing.TB, repository domain.UserRepository, ctx context.Context) seeder.Seeder[domain.User] {
	return seeder.New(t, func(value domain.User) error {
		_, err := repository.Upsert(ctx, value)
		return err
	})
}

type usersBuilder struct {
	fixture.Builder[domain.User]
}

// Users is the generated fluent fixture for domain.User.
var Users = usersBuilder{Builder: fixture.NewGeneratedBuilder(RandomUser)}

// WithID sets ID on a derived fixture.
func (b usersBuilder) WithID(value int) usersBuilder {
	b.Builder = b.Set(func(target *domain.User) { target.ID = value })
	return b
}

// WithBalance sets Balance on a derived fixture.
func (b usersBuilder) WithBalance(value int64) usersBuilder {
	b.Builder = b.Set(func(target *domain.User) { target.Balance = value })
	return b
}

// WithName sets Name on a derived fixture.
func (b usersBuilder) WithName(value string) usersBuilder {
	b.Builder = b.Set(func(target *domain.User) { target.Name = value })
	return b
}

// WithEmail sets Email on a derived fixture.
func (b usersBuilder) WithEmail(value string) usersBuilder {
	b.Builder = b.Set(func(target *domain.User) { target.Email = value })
	return b
}

// WithActive sets Active on a derived fixture.
func (b usersBuilder) WithActive(value bool) usersBuilder {
	b.Builder = b.Set(func(target *domain.User) { target.Active = value })
	return b
}

// WithRole sets Role on a derived fixture.
func (b usersBuilder) WithRole(value domain.Role) usersBuilder {
	b.Builder = b.Set(func(target *domain.User) { target.Role = value })
	return b
}

// WithCreatedAt sets CreatedAt on a derived fixture.
func (b usersBuilder) WithCreatedAt(value time.Time) usersBuilder {
	b.Builder = b.Set(func(target *domain.User) { target.CreatedAt = value })
	return b
}

// WithTags sets Tags on a derived fixture.
func (b usersBuilder) WithTags(value []string) usersBuilder {
	b.Builder = b.Set(func(target *domain.User) { target.Tags = value })
	return b
}

// NewUsersDB creates an in-memory database keyed by ID.
func NewUsersDB(seed ...domain.User) memdb.DB[domain.User] {
	return memdb.New(func(value domain.User) int { return value.ID }, seed...)
}

// DB creates an in-memory database for Users.
func (usersBuilder) DB(seed ...domain.User) memdb.DB[domain.User] { return NewUsersDB(seed...) }

// Doubles groups every generated spy for one test.
type Doubles struct {
	Mailer   *MailerSpy
	UserRepo *UserRepoSpy
}

// NewDoubles composes and registers every generated spy around the supplied implementations.
func NewDoubles(t *testing.T, mailer domain.Mailer, userRepo domain.UserRepository) *Doubles {
	value := &Doubles{
		Mailer:   NewMailerSpy(t, mailer),
		UserRepo: NewUserRepoSpy(t, userRepo),
	}
	return value
}
