// Code generated by testigo-gen. DO NOT EDIT.

package testkit

import (
	"context"
	"testing"
	"time"

	"github.com/lautaromei/testigo"
	"github.com/lautaromei/testigo/fixture"
	"github.com/lautaromei/testigo/internal/testigogen/testdata/domain"
	"github.com/lautaromei/testigo/memdb"
	"github.com/lautaromei/testigo/random"
	"github.com/lautaromei/testigo/seeder"
)

// RandomUser returns a fresh random domain.User.
func RandomUser() domain.User {
	return domain.User{
		ID:        random.ID(),
		Balance:   int64(random.Int()),
		Name:      random.Name(),
		Email:     random.Email(),
		Active:    random.Bool(),
		Role:      random.Pick(domain.RoleAdmin, domain.RoleMember),
		CreatedAt: random.Date(),
	}
}

type defaultUsersBuilder struct {
	fixture.Builder[domain.User]
}

// DefaultUsers is the generated fluent fixture for domain.User.
var DefaultUsers = defaultUsersBuilder{Builder: fixture.NewGeneratedBuilder(defaultUser)}

// WithID sets ID on a derived fixture.
func (b defaultUsersBuilder) WithID(value int) defaultUsersBuilder {
	b.Builder = b.Set(func(target *domain.User) { target.ID = value })
	return b
}

// WithBalance sets Balance on a derived fixture.
func (b defaultUsersBuilder) WithBalance(value int64) defaultUsersBuilder {
	b.Builder = b.Set(func(target *domain.User) { target.Balance = value })
	return b
}

// WithName sets Name on a derived fixture.
func (b defaultUsersBuilder) WithName(value string) defaultUsersBuilder {
	b.Builder = b.Set(func(target *domain.User) { target.Name = value })
	return b
}

// WithEmail sets Email on a derived fixture.
func (b defaultUsersBuilder) WithEmail(value string) defaultUsersBuilder {
	b.Builder = b.Set(func(target *domain.User) { target.Email = value })
	return b
}

// WithActive sets Active on a derived fixture.
func (b defaultUsersBuilder) WithActive(value bool) defaultUsersBuilder {
	b.Builder = b.Set(func(target *domain.User) { target.Active = value })
	return b
}

// WithRole sets Role on a derived fixture.
func (b defaultUsersBuilder) WithRole(value domain.Role) defaultUsersBuilder {
	b.Builder = b.Set(func(target *domain.User) { target.Role = value })
	return b
}

// WithCreatedAt sets CreatedAt on a derived fixture.
func (b defaultUsersBuilder) WithCreatedAt(value time.Time) defaultUsersBuilder {
	b.Builder = b.Set(func(target *domain.User) { target.CreatedAt = value })
	return b
}

// WithTags sets Tags on a derived fixture.
func (b defaultUsersBuilder) WithTags(value []string) defaultUsersBuilder {
	b.Builder = b.Set(func(target *domain.User) { target.Tags = value })
	return b
}

// MailerSpy implements domain.Mailer and records every call.
type MailerSpy struct {
	testigo.Spy
	BroadcastFunc func(ctx context.Context, to ...string) (int, error)
	PingFunc      func()
	SendFunc      func(ctx context.Context, to string) error
}

var _ domain.Mailer = (*MailerSpy)(nil)

func (s *MailerSpy) Broadcast(ctx context.Context, to ...string) (int, error) {
	s.Call(ctx, to)
	if s.BroadcastFunc != nil {
		return s.BroadcastFunc(ctx, to...)
	}
	var result0 int
	var result1 error
	return result0, result1
}

func (s *MailerSpy) Ping() {
	s.Call()
	if s.PingFunc != nil {
		s.PingFunc()
		return
	}
	return
}

func (s *MailerSpy) Send(ctx context.Context, to string) error {
	s.Call(ctx, to)
	if s.SendFunc != nil {
		return s.SendFunc(ctx, to)
	}
	var result0 error
	return result0
}

// NewMailerSpy creates and registers a pristine MailerSpy.
func NewMailerSpy(t *testing.T, configure ...func(*MailerSpy)) *MailerSpy {
	value := &MailerSpy{}
	for _, configure := range configure {
		if configure != nil {
			configure(value)
		}
	}
	return testigo.NewDouble(t, value)
}

// UserRepoSpy implements domain.UserRepository and records every call.
type UserRepoSpy struct {
	testigo.Spy
	UpsertFunc func(ctx context.Context, user domain.User) (domain.User, error)
}

var _ domain.UserRepository = (*UserRepoSpy)(nil)

func (s *UserRepoSpy) Upsert(ctx context.Context, user domain.User) (domain.User, error) {
	s.Call(ctx, user)
	if s.UpsertFunc != nil {
		return s.UpsertFunc(ctx, user)
	}
	var result0 domain.User
	var result1 error
	return result0, result1
}

// NewUserRepoSpy creates and registers a pristine UserRepoSpy.
func NewUserRepoSpy(t *testing.T, configure ...func(*UserRepoSpy)) *UserRepoSpy {
	value := &UserRepoSpy{}
	for _, configure := range configure {
		if configure != nil {
			configure(value)
		}
	}
	return testigo.NewDouble(t, value)
}

// NewUserRepoSeeder adapts domain.UserRepository.Upsert to a typed seeder.
func NewUserRepoSeeder(t testing.TB, repository domain.UserRepository, ctx context.Context) seeder.Seeder[domain.User] {
	return seeder.New(t, func(value domain.User) error {
		_, err := repository.Upsert(ctx, value)
		return err
	})
}

type usersBuilder struct {
	fixture.Builder[domain.User]
}

// Users is the generated fluent fixture for domain.User.
var Users = usersBuilder{Builder: fixture.NewGeneratedBuilder(RandomUser)}

// WithID sets ID on a derived fixture.
func (b usersBuilder) WithID(value int) usersBuilder {
	b.Builder = b.Set(func(target *domain.User) { target.ID = value })
	return b
}

// WithBalance sets Balance on a derived fixture.
func (b usersBuilder) WithBalance(value int64) usersBuilder {
	b.Builder = b.Set(func(target *domain.User) { target.Balance = value })
	return b
}

// WithName sets Name on a derived fixture.
func (b usersBuilder) WithName(value string) usersBuilder {
	b.Builder = b.Set(func(target *domain.User) { target.Name = value })
	return b
}

// WithEmail sets Email on a derived fixture.
func (b usersBuilder) WithEmail(value string) usersBuilder {
	b.Builder = b.Set(func(target *domain.User) { target.Email = value })
	return b
}

// WithActive sets Active on a derived fixture.
func (b usersBuilder) WithActive(value bool) usersBuilder {
	b.Builder = b.Set(func(target *domain.User) { target.Active = value })
	return b
}

// WithRole sets Role on a derived fixture.
func (b usersBuilder) WithRole(value domain.Role) usersBuilder {
	b.Builder = b.Set(func(target *domain.User) { target.Role = value })
	return b
}

// WithCreatedAt sets CreatedAt on a derived fixture.
func (b usersBuilder) WithCreatedAt(value time.Time) usersBuilder {
	b.Builder = b.Set(func(target *domain.User) { target.CreatedAt = value })
	return b
}

// WithTags sets Tags on a derived fixture.
func (b usersBuilder) WithTags(value []string) usersBuilder {
	b.Builder = b.Set(func(target *domain.User) { target.Tags = value })
	return b
}

// NewUsersDB creates an in-memory database keyed by ID.
func NewUsersDB(seed ...domain.User) memdb.DB[domain.User] {
	return memdb.New(func(value domain.User) int { return value.ID }, seed...)
}

// DB creates an in-memory database for Users.
func (usersBuilder) DB(seed ...domain.User) memdb.DB[domain.User] { return NewUsersDB(seed...) }

// Doubles groups every generated spy for one test.
type Doubles struct {
	Mailer   *MailerSpy
	UserRepo *UserRepoSpy
}

// NewDoubles constructs, optionally configures, and registers every generated spy.
func NewDoubles(t *testing.T, configure ...func(*Doubles)) *Doubles {
	value := &Doubles{
		Mailer:   &MailerSpy{},
		UserRepo: &UserRepoSpy{},
	}
	for _, configure := range configure {
		if configure != nil {
			configure(value)
		}
	}
	value.Mailer = testigo.NewDouble(t, value.Mailer)
	value.UserRepo = testigo.NewDouble(t, value.UserRepo)
	return value
}
